@startuml tcp-basic-interactions
skinparam sequenceMessageAlign center

Client -> Server : Establish connection
Server ---> Client : Connection established


== Download file ==

Client -> Server : SHOW file2.txt
Server ---> Client : Sending file2.txt ...

== Upload file ==

Client -> Server : UPLOAD [filesize]
Server ---> Client : OK

Client -> Server : Sending file2.txt
Server ---> Client : Received

@enduml

